spring.application.name=sale

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/coffee
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.employee-datasource.driver-class-name=org.h2.Driver
spring.employee-datasource.h2.url=jdbc:h2:file:./employee;AUTO_SERVER=TRUE
spring.employee-datasource.h2.username=employee
spring.employee-datasource.h2.password=employee

jwt.secret=4117f8813ea4d2bab234270d1002a7223bf4917f962babc76b5774116130008a

server.port=8888
