playerImage=resources/images/player.png
playerOnTargetImage=resources/images/playerOnTarget.png
boxImage=resources/images/box.png
boxOnTargetImage=resources/images/boxOnTarget.png
wallImage=resources/images/wall.png
areaImage=resources/images/area.png
targetImage=resources/images/target.png