title=Notepad MVC Pattern
icon=images/iconForFrame.png

menubar=file edit view format help

file=new open save saveAs import export - saveToServer readFromServer - print - insertImage - exit
fileLabel=File

newLabel=New
newAction=NewDocument
newImage=images/filemenu/new.png
newKeyStroke=control N
newTooltip=New

openLabel=Open
openAction=OpenDocument
openImage=images/filemenu/open.png
openKeyStroke=control O
openTooltip=Open

saveLabel=Save
saveAction=SaveDocument
saveImage=images/filemenu/save.png
saveKeyStroke=control S
saveTooltip=Save

saveAsLabel=SaveAs
saveAsAction=SaveAsDocument
saveAsImage=images/filemenu/saveAs.png
saveAsKeyStroke=control alt S
saveAsTooltip=Save

importLabel=Import
importAction=Import
importImage=images/filemenu/import.png
importKeyStroke=control alt O

exportLabel=Export
exportAction=Export
exportImage=images/filemenu/export.png
exportKeyStroke=control alt S

saveToServerLabel=Save To Server
saveToServerAction=SaveToServer
saveToServerImage=images/filemenu/save_to_server.png
saveToServerKeyStroke=control G

readFromServerLabel=Read From Server
readFromServerAction=ReadFromServer
readFromServerImage=images/filemenu/open.png
readFromServerKeyStroke=control R

printLabel=Print
printAction=Print
printImage=images/filemenu/print.png
printKeyStroke=control P

insertImageLabel=Insert Image
insertImageAction=InsertImage
insertImageImage=images/filemenu/insertImage.png
insertImageKeyStroke=control I

exitLabel=Exit
exitAction=Exit
exitImage=images/filemenu/exit.png
exitKeyStroke=control Q

edit=cut copy paste clear - find findPrevious findNext goTo - selectAll timeAndDate - undo redo
editLabel=Edit

cutLabel=Cut
cutAction=Cut
cutImage=images/editmenu/cut.png
cutKeyStroke=control X
cutTooltip=Cut

copyLabel=Copy
copyAction=Copy
copyImage=images/editmenu/copy.png
copyKeyStroke=control C
copyTooltip=Copy

pasteLabel=Paste
pasteAction=Paste
pasteImage=images/editmenu/paste.png
pasteKeyStroke=control V
pasteTooltip=Paste

clearLabel=Clear
clearAction=Clear
clearImage=images/editmenu/clear.png
clearKeyStroke=DELETE

findPreviousLabel=Find Prev
findPreviousAction=FindPrevious
findPreviousImage=images/editmenu/findprev.png
findPreviousKeyStroke=control UP

findLabel=Find
findAction=Find
findImage=images/editmenu/find.png
findKeyStroke=control F

findNextLabel=Find Next
findNextAction=FindNext
findNextImage=images/editmenu/findnext.png
findNextKeyStroke=control DOWN

goToLabel=Go
goToAction=Go
goToImage=images/editmenu/goTo.png
goToKeyStroke=control shift G

selectAllLabel=Select all
selectAllAction=SelectAll
selectAllImage=images/editmenu/selectAll.png
selectAllKeyStroke=control A
selectAllTooltip=Select all

timeAndDateLabel=Time and Date
timeAndDateAction=TimeAndDate
timeAndDateImage=images/editmenu/timeAndDate.png
timeAndDateKeyStroke=F5

undoLabel=Undo
undoAction=Undo
undoImage=images/editmenu/undo.png
undoKeyStroke=control Z

redoLabel=Redo
redoAction=Redo
redoImage=images/editmenu/redo.png
redoKeyStroke=control Y


format=font
formatLabel=Format



fontLabel=Font
fontAction=Font
fontImage=images/formatmenu/font.png
fontKeyStroke=control T

view=statusBar
viewLabel=View

statusBarLabel=Status Bar
statusBarAction=StatusBar
statusBarImage=images/viewmenu/statusBar.png

help=about
helpLabel=Help

aboutLabel=About
aboutAction=About
aboutImage=images/helpmenu/about.png

toolbar=new open save - cut copy paste selectAll - synchronize

synchronizeLabel=Synchronize
synchronizeAction=Synchronize
synchronizeImage=images/toolbar/syncDisable.png
synchronizeTooltip=Synchronize

